/* eslint-disable @typescript-eslint/naming-convention */

export interface Paciente {
    id:                       number;
    rut:                      string;
    nombre:                   string;
    apellido:                 string;
    sexo:                     string;
    direccion:                string;
    region:                   string;
    comuna:                   string;
    fallecido:                number;
    TlfActivo:                string;
    tlf_movil:                string;
    tlf_fijo:                 string;
    TelefonosExtras:          string;
    EmailActivo:              string;
    email:                    string;
    MailExtras:               string;
    contacto:                 string;
    tlf_movil_cont:           string;
    email_cont:               string;
    Parentesco:               string;
    fec_prox_gestion:         Date | string;
    fec_ult_gestion:          Date | string;
    fec_pam_antiguo:          Date | string;
    FecUltPago:               Date | string;
    FecCarga:                 Date;
    FecContactado:            string;
    FecAsignacion:            Date | string;
    FecIniAsignacion:         Date | string;
    FecLimite:                Date | string;
    rut_isapres_pam:          string;
    Tratamiento:              boolean;
    Pagare:                   boolean;
    SwGestionMasiva:          boolean;
    Estado:                   string;
    TipoPrestaciones:         string;
    cant_pams:                number;
    Sms:                      number;
    Emails:                   number;
    Llamadas:                 number;
    Otros:                    number;
    EjeAsignado:              string;
    usr_asignado:             number;
    deuda_actual:             string;
    deuda_inicial:            string;
    deuda_copago_inicial:     string;
    deuda_copago_actual:      string;
    deuda_xbonificar_inicial: string;
    deuda_xbonificar_actual:  string;
    MtoDeudaReal:             string;
    nombre_isapre_actual:     string;
    comentarios:              string;
    createdAt:                null;
    updatedAt:                null;
}
